const SEATING_ROWS = 3
const SEATING_COLS = 11
const MAX_SEAT_REQUEST = 10
const NOT_ENOUGH_SEATS_MESSAGE = 'Not Available'

exports.SEATING_ROWS = SEATING_ROWS
exports.SEATING_COLS = SEATING_COLS
exports.MAX_SEAT_REQUEST = MAX_SEAT_REQUEST
exports.NOT_ENOUGH_SEATS_MESSAGE = NOT_ENOUGH_SEATS_MESSAGE
